### ISSUE TITLE
Issue with basic example

### ISSUE THREAD

**Issue by Schmay00** [AngelosPsy/multifear#9]
Hi!
Thank you for putting together the package, I'm really excited about it. Today I tried to use it for the first time, but run into an error message. Can you help me solve it?

Error in dplyr::mutate(., method = ttl$alternative, x = "cs", y = dv, : object 'ttl' not found
6.
dplyr::mutate(., method = ttl$alternative, x = "cs", y = dv, exclusion = exclusion, cut_off = cut_off, model = "t-test", controls = NA, framework = "NHST")
5.
dplyr::select(., x, y, exclusion, cut_off, model, controls, method, p.value, effect.size, effect.size.ma, effect.size.ma.lci, effect.size.ma.hci, estimate, statistic, conf.low, conf.high, framework)
4.
dplyr::mutate(., data_used = list(data))
3.
ttl %>% dplyr::mutate(method = ttl$alternative, x = "cs", y = dv, exclusion = exclusion, cut_off = cut_off, model = "t-test", controls = NA, framework = "NHST") %>% dplyr::select(x, y, exclusion, cut_off, model, controls, method, p.value, effect.size, ...
2.
multifear::t_test_mf(cs1 = cs1, cs2 = cs2, data = data, subj = subj, paired = paired, phase = phase, exclusion = exclusion, cut_off = cut_off, meta.effect = meta.effect)
1.
multifear::universe_cs(cs1 = cs1, cs2 = cs2, data = Mega_wideNA, subj = "ID_Maya", group = NULL, phase = "recall", include_bayes = FALSE)

**Comment by AngelosPsy** [comment]
Hello @Schmay00,

Thank you for your message. Could you maybe provide a reproducible example so that I can look more into it? I can see the error but not sure how it was generated. Having an example will help a lot in trying to solve the problem.

**Comment by Schmay00** [comment]
Hi AngeloPsy

I think there must have been a typo somewhere, it worked now. Thanks for your quick response!
